/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import databaseRepository.DatabseConnection;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import model.Nastavnik;
import model.Zvanje;

/**
 *
 * @author PC
 */
public class frmDodajNastavnika extends javax.swing.JPanel {

    /**
     * Creates new form frmDodajNastavnika
     */
    public frmDodajNastavnika() {
        initComponents();
        prepareView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        jcbZvanja = new javax.swing.JComboBox<>();
        btnDodajNastavnika = new javax.swing.JButton();

        jLabel2.setText("IME: ");

        jLabel3.setText("PREZIME");

        jLabel4.setText("ZVANJE:");

        btnDodajNastavnika.setText("Dodaj nastavnika");
        btnDodajNastavnika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajNastavnikaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel2)
                        .addGap(57, 57, 57)
                        .addComponent(txtName))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLastName, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                            .addComponent(jcbZvanja, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnDodajNastavnika)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jcbZvanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(btnDodajNastavnika)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajNastavnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajNastavnikaActionPerformed
        String firstname=txtName.getText();
        String lastanme=txtLastName.getText();
        boolean validno=ValidirajPodatke(firstname,lastanme);
        if(validno==false){
            return;
        }
        System.out.println("isptavni podaci");
        
        DatabseConnection connection=new DatabseConnection();
        connection.Connect();
        
        try {
            Nastavnik nastavnik = new Nastavnik(1, firstname, lastanme, (Zvanje) jcbZvanja.getSelectedItem());
            connection.addNastavnik(nastavnik);
            JOptionPane.showMessageDialog(this, "Nastavnik uspesno dodat");
            txtLastName.setText("");
            txtName.setText("");
            jcbZvanja.setSelectedIndex(-1);
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
        
    }//GEN-LAST:event_btnDodajNastavnikaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajNastavnika;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox<Object> jcbZvanja;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables

    private void prepareView() {
        
        DatabseConnection connection=new DatabseConnection();
        connection.Connect();
        List<Zvanje> zvanja=new ArrayList<Zvanje>();
        zvanja=connection.GetAllZvanja();
        
        for (Zvanje zvanje : zvanja) {
            jcbZvanja.addItem(zvanje);
        }
        jcbZvanja.setSelectedIndex(-1);
    }

    private boolean ValidirajPodatke(String firstname, String lastanme) {
            for (int i = 0; i < firstname.length(); i++) {
            if(!(Character.isAlphabetic(firstname.charAt(i)))||firstname.length()==0){
                JOptionPane.showMessageDialog(this, "Lose uneto ime");
                return false;
            }
            }
            for (int i = 0; i < lastanme.length(); i++) {
            if(!(Character.isAlphabetic(lastanme.charAt(i)))||lastanme.length()==0){
                JOptionPane.showMessageDialog(this, "Lose uneto prezime");
                return false;
            }
            }
            
            if(!Character.isUpperCase(firstname.charAt(0))){
                JOptionPane.showMessageDialog(this, "Ime mora poceti velikim slovom");
                return false;
            }
             if(!Character.isUpperCase(lastanme.charAt(0))){
                JOptionPane.showMessageDialog(this, "Prezime mora poceti velikim slovom");
            return false;
             } 
             if(jcbZvanja.getSelectedItem()==null){
                 JOptionPane.showMessageDialog(this, "Morate selktovati zvanje");

             }
             
             return true;
        
    }


}

